Devise
renius/appartment_management pull request #11
Opened 2017-04-29 23:00 UTC by medaved

Task #1 complete.
https://appartz.herokuapp.com/users/sign_up

2017-04-29 23:05 UTC, AlexanderMint commented
Стоит в локали добавить русский язык и перевести письма. Если @renius не против, было бы правильным сделать мультиязычным интерфейс.

2017-04-29 23:06 UTC, AlexanderMint commented
Так же из конфига девайса убрать весь мусор в виде комментариев

2017-04-29 23:11 UTC, AlexanderMint commented
И если не будет подтверждения, то стоит и письма соответствующие удалить

2017-04-29 23:11 UTC, AlexanderMint requested changes

2017-04-29 23:11 UTC, AlexanderMint commented on db/schema.rb
> +    t.string   "email",                  default: "", null: false
index

2017-05-01 09:40 UTC, renius commented
> Стоит в локали добавить русский язык и перевести письма. Если @renius не против, было бы правильным сделать мультиязычным интерфейс.

@AlexanderMint Лучше оформить новым pr/issue

2017-05-01 14:12 UTC, AlexanderMint commented
@renius я просто не вижу сложностей сразу хорошо делать...

2017-05-01 15:40 UTC, medaved commented on db/schema.rb
> +    t.string   "email",                  default: "", null: false
как лучше поступить, эту миграцию поправить или новую сделать

2017-05-01 15:44 UTC, medaved commented
@AlexanderMin, я думаю @renius  предлагает решать проблемы, по мере их поступления. 
Сделать не проблема, но, не известно пригодится ли данное решение или нет.

2017-05-01 16:12 UTC, renius commented
> @renius я просто не вижу сложностей сразу хорошо делать...
@medaved @AlexanderMint лучше делать короткими итерациями, чем раньше основа узла будет в рабочем состоянии тем больше появится мелких задач которые смогут решать разные люди независимо

2017-05-01 18:01 UTC, AlexanderMint commented
По опыту, начать делать правильно сразу - не сложно, тем более rails дает все инструменты для этого, а вот потом искать текст, переводить его, это геморно да и код не красиво выглядит.

А так ок, мне в принципе все равно

2017-05-01 23:31 UTC, medaved commented
Хорошо, оба подхода по своему правильные по своему, но давайте на одном остановимся, что ещё исправить, что бы, задачу закрыть?

2017-05-02 08:06 UTC, AlexanderMint commented
@medaved я же выше написал что исправить

2017-05-03 10:42 UTC, renius submitted a review, later dismissed

2017-05-03 14:38 UTC, renius approved these changes

2017-05-03 14:38 UTC, merged

2017-05-03 14:46 UTC, AlexanderMint commented
@medaved не стоит пренебрегать индексами, просто оставлю тут

``` ruby
t.string "email", default: "", null: false, index: true
```

и [статья на Хабре](https://habrahabr.ru/post/247373/)

2017-05-03 14:53 UTC, medaved commented
@AlexanderMint , это не то же самое: add_index "users", ["email"], name: "index_users_on_email", unique: true, using: :btree